/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.ui;

import ca.ubc.stat.blang.ui.AbstractBlangDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BlangDslUiModule extends AbstractBlangDslUiModule {
  public BlangDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
