/*
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BlangDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ca/ubc/stat/blang/parser/antlr/internal/InternalBlangDsl.tokens");
	}
}
