/*
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.parser.antlr;

import ca.ubc.stat.blang.parser.antlr.internal.InternalBlangDslParser;
import ca.ubc.stat.blang.services.BlangDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BlangDslParser extends AbstractAntlrParser {

	@Inject
	private BlangDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBlangDslParser createParser(XtextTokenStream stream) {
		return new InternalBlangDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BlangModel";
	}

	public BlangDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BlangDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
