/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.ui.contentassist;

import ca.ubc.stat.blang.ui.contentassist.AbstractBlangDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BlangDslProposalProvider extends AbstractBlangDslProposalProvider {
}
