/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.scoping;

import ca.ubc.stat.blang.scoping.AbstractBlangDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BlangDslScopeProvider extends AbstractBlangDslScopeProvider {
}
