/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.blangDsl.impl;

import ca.ubc.stat.blang.blangDsl.BlangDslPackage;
import ca.ubc.stat.blang.blangDsl.BlangModel;
import ca.ubc.stat.blang.blangDsl.Const;
import ca.ubc.stat.blang.blangDsl.Laws;
import ca.ubc.stat.blang.blangDsl.ModelVar;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.xtext.xtype.XImportSection;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Blang Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl#getName <em>Name</em>}</li>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl#getImportSection <em>Import Section</em>}</li>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl#getVars <em>Vars</em>}</li>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl#getConsts <em>Consts</em>}</li>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl#getLaws <em>Laws</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BlangModelImpl extends MinimalEObjectImpl.Container implements BlangModel
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getImportSection() <em>Import Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImportSection()
   * @generated
   * @ordered
   */
  protected XImportSection importSection;

  /**
   * The cached value of the '{@link #getVars() <em>Vars</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVars()
   * @generated
   * @ordered
   */
  protected EList<ModelVar> vars;

  /**
   * The cached value of the '{@link #getConsts() <em>Consts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConsts()
   * @generated
   * @ordered
   */
  protected EList<Const> consts;

  /**
   * The cached value of the '{@link #getLaws() <em>Laws</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLaws()
   * @generated
   * @ordered
   */
  protected Laws laws;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BlangModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlangDslPackage.Literals.BLANG_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlangDslPackage.BLANG_MODEL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XImportSection getImportSection()
  {
    return importSection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetImportSection(XImportSection newImportSection, NotificationChain msgs)
  {
    XImportSection oldImportSection = importSection;
    importSection = newImportSection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BlangDslPackage.BLANG_MODEL__IMPORT_SECTION, oldImportSection, newImportSection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImportSection(XImportSection newImportSection)
  {
    if (newImportSection != importSection)
    {
      NotificationChain msgs = null;
      if (importSection != null)
        msgs = ((InternalEObject)importSection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BlangDslPackage.BLANG_MODEL__IMPORT_SECTION, null, msgs);
      if (newImportSection != null)
        msgs = ((InternalEObject)newImportSection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BlangDslPackage.BLANG_MODEL__IMPORT_SECTION, null, msgs);
      msgs = basicSetImportSection(newImportSection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlangDslPackage.BLANG_MODEL__IMPORT_SECTION, newImportSection, newImportSection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ModelVar> getVars()
  {
    if (vars == null)
    {
      vars = new EObjectContainmentEList<ModelVar>(ModelVar.class, this, BlangDslPackage.BLANG_MODEL__VARS);
    }
    return vars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Const> getConsts()
  {
    if (consts == null)
    {
      consts = new EObjectContainmentEList<Const>(Const.class, this, BlangDslPackage.BLANG_MODEL__CONSTS);
    }
    return consts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Laws getLaws()
  {
    return laws;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLaws(Laws newLaws, NotificationChain msgs)
  {
    Laws oldLaws = laws;
    laws = newLaws;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BlangDslPackage.BLANG_MODEL__LAWS, oldLaws, newLaws);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLaws(Laws newLaws)
  {
    if (newLaws != laws)
    {
      NotificationChain msgs = null;
      if (laws != null)
        msgs = ((InternalEObject)laws).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BlangDslPackage.BLANG_MODEL__LAWS, null, msgs);
      if (newLaws != null)
        msgs = ((InternalEObject)newLaws).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BlangDslPackage.BLANG_MODEL__LAWS, null, msgs);
      msgs = basicSetLaws(newLaws, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BlangDslPackage.BLANG_MODEL__LAWS, newLaws, newLaws));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BlangDslPackage.BLANG_MODEL__IMPORT_SECTION:
        return basicSetImportSection(null, msgs);
      case BlangDslPackage.BLANG_MODEL__VARS:
        return ((InternalEList<?>)getVars()).basicRemove(otherEnd, msgs);
      case BlangDslPackage.BLANG_MODEL__CONSTS:
        return ((InternalEList<?>)getConsts()).basicRemove(otherEnd, msgs);
      case BlangDslPackage.BLANG_MODEL__LAWS:
        return basicSetLaws(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BlangDslPackage.BLANG_MODEL__NAME:
        return getName();
      case BlangDslPackage.BLANG_MODEL__IMPORT_SECTION:
        return getImportSection();
      case BlangDslPackage.BLANG_MODEL__VARS:
        return getVars();
      case BlangDslPackage.BLANG_MODEL__CONSTS:
        return getConsts();
      case BlangDslPackage.BLANG_MODEL__LAWS:
        return getLaws();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BlangDslPackage.BLANG_MODEL__NAME:
        setName((String)newValue);
        return;
      case BlangDslPackage.BLANG_MODEL__IMPORT_SECTION:
        setImportSection((XImportSection)newValue);
        return;
      case BlangDslPackage.BLANG_MODEL__VARS:
        getVars().clear();
        getVars().addAll((Collection<? extends ModelVar>)newValue);
        return;
      case BlangDslPackage.BLANG_MODEL__CONSTS:
        getConsts().clear();
        getConsts().addAll((Collection<? extends Const>)newValue);
        return;
      case BlangDslPackage.BLANG_MODEL__LAWS:
        setLaws((Laws)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BlangDslPackage.BLANG_MODEL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case BlangDslPackage.BLANG_MODEL__IMPORT_SECTION:
        setImportSection((XImportSection)null);
        return;
      case BlangDslPackage.BLANG_MODEL__VARS:
        getVars().clear();
        return;
      case BlangDslPackage.BLANG_MODEL__CONSTS:
        getConsts().clear();
        return;
      case BlangDslPackage.BLANG_MODEL__LAWS:
        setLaws((Laws)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BlangDslPackage.BLANG_MODEL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case BlangDslPackage.BLANG_MODEL__IMPORT_SECTION:
        return importSection != null;
      case BlangDslPackage.BLANG_MODEL__VARS:
        return vars != null && !vars.isEmpty();
      case BlangDslPackage.BLANG_MODEL__CONSTS:
        return consts != null && !consts.isEmpty();
      case BlangDslPackage.BLANG_MODEL__LAWS:
        return laws != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //BlangModelImpl
