/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.blangDsl.impl;

import ca.ubc.stat.blang.blangDsl.BlangDslPackage;
import ca.ubc.stat.blang.blangDsl.Laws;
import ca.ubc.stat.blang.blangDsl.ModelComponent;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Laws</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.impl.LawsImpl#getModelComponents <em>Model Components</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LawsImpl extends MinimalEObjectImpl.Container implements Laws
{
  /**
   * The cached value of the '{@link #getModelComponents() <em>Model Components</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelComponents()
   * @generated
   * @ordered
   */
  protected EList<ModelComponent> modelComponents;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LawsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlangDslPackage.Literals.LAWS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ModelComponent> getModelComponents()
  {
    if (modelComponents == null)
    {
      modelComponents = new EObjectContainmentEList<ModelComponent>(ModelComponent.class, this, BlangDslPackage.LAWS__MODEL_COMPONENTS);
    }
    return modelComponents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BlangDslPackage.LAWS__MODEL_COMPONENTS:
        return ((InternalEList<?>)getModelComponents()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BlangDslPackage.LAWS__MODEL_COMPONENTS:
        return getModelComponents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BlangDslPackage.LAWS__MODEL_COMPONENTS:
        getModelComponents().clear();
        getModelComponents().addAll((Collection<? extends ModelComponent>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BlangDslPackage.LAWS__MODEL_COMPONENTS:
        getModelComponents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BlangDslPackage.LAWS__MODEL_COMPONENTS:
        return modelComponents != null && !modelComponents.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LawsImpl
