/*
 * generated by Xtext 2.24.0
 */
package ca.ubc.stat.blang.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class BlangDslWebModule extends AbstractBlangDslWebModule {
}
