/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.validation;

import ca.ubc.stat.blang.validation.AbstractBlangDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BlangDslValidator extends AbstractBlangDslValidator {
}
