/*
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.ui;

import ca.ubc.stat.blang.ui.internal.BlangActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BlangDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BlangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BlangActivator.getInstance().getInjector(BlangActivator.CA_UBC_STAT_BLANG_BLANGDSL);
	}
	
}
