/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang;

import ca.ubc.stat.blang.AbstractBlangDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BlangDslRuntimeModule extends AbstractBlangDslRuntimeModule {
}
