/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang;

import ca.ubc.stat.blang.BlangDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BlangDslStandaloneSetup extends BlangDslStandaloneSetupGenerated {
  public static void doSetup() {
    BlangDslStandaloneSetup _blangDslStandaloneSetup = new BlangDslStandaloneSetup();
    _blangDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
