/*
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractBlangDslScopeProvider extends XbaseBatchScopeProvider {
}
