/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class BlangDslLabelProvider extends XbaseLabelProvider {
  @Inject
  public BlangDslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
