/*
 * generated by Xtext 2.24.0
 */
package ca.ubc.stat.blang.ui;

import ca.ubc.stat.blang.ui.internal.BlangActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BlangDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BlangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BlangActivator activator = BlangActivator.getInstance();
		return activator != null ? activator.getInjector(BlangActivator.CA_UBC_STAT_BLANG_BLANGDSL) : null;
	}

}
