/*
 * generated by Xtext 2.24.0
 */
package ca.ubc.stat.blang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BlangDslUiModule extends AbstractBlangDslUiModule {

	public BlangDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
