/*
 * generated by Xtext 2.24.0
 */
package ca.ubc.stat.blang.ide;

import ca.ubc.stat.blang.BlangDslRuntimeModule;
import ca.ubc.stat.blang.BlangDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BlangDslIdeSetup extends BlangDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BlangDslRuntimeModule(), new BlangDslIdeModule()));
	}
	
}
