/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.blangDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.ubc.stat.blang.blangDsl.BlangDslFactory
 * @model kind="package"
 * @generated
 */
public interface BlangDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "blangDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ubc.ca/stat/blang/BlangDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "blangDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BlangDslPackage eINSTANCE = ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl.init();

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl <em>Blang Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getBlangModel()
   * @generated
   */
  int BLANG_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANG_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANG_MODEL__IMPORT_SECTION = 1;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANG_MODEL__VARS = 2;

  /**
   * The feature id for the '<em><b>Laws</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANG_MODEL__LAWS = 3;

  /**
   * The number of structural features of the '<em>Blang Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANG_MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.VarsImpl <em>Vars</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.VarsImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getVars()
   * @generated
   */
  int VARS = 1;

  /**
   * The feature id for the '<em><b>Random Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS__RANDOM_VARS = 0;

  /**
   * The feature id for the '<em><b>Param Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS__PARAM_VARS = 1;

  /**
   * The feature id for the '<em><b>Consts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS__CONSTS = 2;

  /**
   * The number of structural features of the '<em>Vars</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.RandomImpl <em>Random</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.RandomImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getRandom()
   * @generated
   */
  int RANDOM = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM__NAME = 1;

  /**
   * The number of structural features of the '<em>Random</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANDOM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.ParamVarImpl <em>Param Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.ParamVarImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getParamVar()
   * @generated
   */
  int PARAM_VAR = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VAR__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VAR__NAME = 1;

  /**
   * The number of structural features of the '<em>Param Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VAR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.ConstImpl <em>Const</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.ConstImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getConst()
   * @generated
   */
  int CONST = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__NAME = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Const</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.VarDeclImpl <em>Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.VarDeclImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getVarDecl()
   * @generated
   */
  int VAR_DECL = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__NAME = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.LawsImpl <em>Laws</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.LawsImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getLaws()
   * @generated
   */
  int LAWS = 6;

  /**
   * The feature id for the '<em><b>Model Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAWS__MODEL_COMPONENTS = 0;

  /**
   * The number of structural features of the '<em>Laws</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAWS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.ModelComponentImpl <em>Model Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.ModelComponentImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getModelComponent()
   * @generated
   */
  int MODEL_COMPONENT = 7;

  /**
   * The number of structural features of the '<em>Model Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_COMPONENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.SupportFactorImpl <em>Support Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.SupportFactorImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getSupportFactor()
   * @generated
   */
  int SUPPORT_FACTOR = 8;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPPORT_FACTOR__PARAMS = MODEL_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPPORT_FACTOR__EXPR = MODEL_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Support Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPPORT_FACTOR_FEATURE_COUNT = MODEL_COMPONENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.LogScaleFactorImpl <em>Log Scale Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.LogScaleFactorImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getLogScaleFactor()
   * @generated
   */
  int LOG_SCALE_FACTOR = 9;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG_SCALE_FACTOR__PARAMS = MODEL_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG_SCALE_FACTOR__EXPR = MODEL_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Log Scale Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOG_SCALE_FACTOR_FEATURE_COUNT = MODEL_COMPONENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.ModelParamImpl <em>Model Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.ModelParamImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getModelParam()
   * @generated
   */
  int MODEL_PARAM = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_PARAM__NAME = MODEL_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Deps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_PARAM__DEPS = MODEL_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_PARAM__RIGHT = MODEL_COMPONENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Model Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_PARAM_FEATURE_COUNT = MODEL_COMPONENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.DependencyImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 11;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__NAME = 1;

  /**
   * The feature id for the '<em><b>Init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__INIT = 2;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.DistributionImpl <em>Distribution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.DistributionImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getDistribution()
   * @generated
   */
  int DISTRIBUTION = 12;

  /**
   * The feature id for the '<em><b>Clazz</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION__CLAZZ = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION__PARAM = 1;

  /**
   * The number of structural features of the '<em>Distribution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.ParamImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getParam()
   * @generated
   */
  int PARAM = 13;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.ConstParamImpl <em>Const Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.ConstParamImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getConstParam()
   * @generated
   */
  int CONST_PARAM = 14;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_PARAM__ID = PARAM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Const Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_PARAM_FEATURE_COUNT = PARAM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ca.ubc.stat.blang.blangDsl.impl.LazyParamImpl <em>Lazy Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.ubc.stat.blang.blangDsl.impl.LazyParamImpl
   * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getLazyParam()
   * @generated
   */
  int LAZY_PARAM = 15;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAZY_PARAM__EXPR = PARAM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lazy Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAZY_PARAM_FEATURE_COUNT = PARAM_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.BlangModel <em>Blang Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blang Model</em>'.
   * @see ca.ubc.stat.blang.blangDsl.BlangModel
   * @generated
   */
  EClass getBlangModel();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.BlangModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.BlangModel#getName()
   * @see #getBlangModel()
   * @generated
   */
  EAttribute getBlangModel_Name();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.BlangModel#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see ca.ubc.stat.blang.blangDsl.BlangModel#getImportSection()
   * @see #getBlangModel()
   * @generated
   */
  EReference getBlangModel_ImportSection();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.BlangModel#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vars</em>'.
   * @see ca.ubc.stat.blang.blangDsl.BlangModel#getVars()
   * @see #getBlangModel()
   * @generated
   */
  EReference getBlangModel_Vars();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.BlangModel#getLaws <em>Laws</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Laws</em>'.
   * @see ca.ubc.stat.blang.blangDsl.BlangModel#getLaws()
   * @see #getBlangModel()
   * @generated
   */
  EReference getBlangModel_Laws();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Vars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vars</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Vars
   * @generated
   */
  EClass getVars();

  /**
   * Returns the meta object for the containment reference list '{@link ca.ubc.stat.blang.blangDsl.Vars#getRandomVars <em>Random Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Random Vars</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Vars#getRandomVars()
   * @see #getVars()
   * @generated
   */
  EReference getVars_RandomVars();

  /**
   * Returns the meta object for the containment reference list '{@link ca.ubc.stat.blang.blangDsl.Vars#getParamVars <em>Param Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param Vars</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Vars#getParamVars()
   * @see #getVars()
   * @generated
   */
  EReference getVars_ParamVars();

  /**
   * Returns the meta object for the containment reference list '{@link ca.ubc.stat.blang.blangDsl.Vars#getConsts <em>Consts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Consts</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Vars#getConsts()
   * @see #getVars()
   * @generated
   */
  EReference getVars_Consts();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Random <em>Random</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Random</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Random
   * @generated
   */
  EClass getRandom();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.Random#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Random#getType()
   * @see #getRandom()
   * @generated
   */
  EReference getRandom_Type();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.Random#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Random#getName()
   * @see #getRandom()
   * @generated
   */
  EAttribute getRandom_Name();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.ParamVar <em>Param Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Var</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ParamVar
   * @generated
   */
  EClass getParamVar();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.ParamVar#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ParamVar#getType()
   * @see #getParamVar()
   * @generated
   */
  EReference getParamVar_Type();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.ParamVar#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ParamVar#getName()
   * @see #getParamVar()
   * @generated
   */
  EAttribute getParamVar_Name();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Const <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Const
   * @generated
   */
  EClass getConst();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.Const#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Const#getType()
   * @see #getConst()
   * @generated
   */
  EReference getConst_Type();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.Const#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Const#getName()
   * @see #getConst()
   * @generated
   */
  EAttribute getConst_Name();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.Const#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Const#getRight()
   * @see #getConst()
   * @generated
   */
  EReference getConst_Right();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.VarDecl <em>Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Decl</em>'.
   * @see ca.ubc.stat.blang.blangDsl.VarDecl
   * @generated
   */
  EClass getVarDecl();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.VarDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see ca.ubc.stat.blang.blangDsl.VarDecl#getType()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_Type();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.VarDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.VarDecl#getName()
   * @see #getVarDecl()
   * @generated
   */
  EAttribute getVarDecl_Name();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.VarDecl#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ca.ubc.stat.blang.blangDsl.VarDecl#getRight()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_Right();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Laws <em>Laws</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Laws</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Laws
   * @generated
   */
  EClass getLaws();

  /**
   * Returns the meta object for the containment reference list '{@link ca.ubc.stat.blang.blangDsl.Laws#getModelComponents <em>Model Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Model Components</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Laws#getModelComponents()
   * @see #getLaws()
   * @generated
   */
  EReference getLaws_ModelComponents();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.ModelComponent <em>Model Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Component</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ModelComponent
   * @generated
   */
  EClass getModelComponent();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.SupportFactor <em>Support Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Support Factor</em>'.
   * @see ca.ubc.stat.blang.blangDsl.SupportFactor
   * @generated
   */
  EClass getSupportFactor();

  /**
   * Returns the meta object for the attribute list '{@link ca.ubc.stat.blang.blangDsl.SupportFactor#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see ca.ubc.stat.blang.blangDsl.SupportFactor#getParams()
   * @see #getSupportFactor()
   * @generated
   */
  EAttribute getSupportFactor_Params();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.SupportFactor#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see ca.ubc.stat.blang.blangDsl.SupportFactor#getExpr()
   * @see #getSupportFactor()
   * @generated
   */
  EReference getSupportFactor_Expr();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.LogScaleFactor <em>Log Scale Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Log Scale Factor</em>'.
   * @see ca.ubc.stat.blang.blangDsl.LogScaleFactor
   * @generated
   */
  EClass getLogScaleFactor();

  /**
   * Returns the meta object for the attribute list '{@link ca.ubc.stat.blang.blangDsl.LogScaleFactor#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see ca.ubc.stat.blang.blangDsl.LogScaleFactor#getParams()
   * @see #getLogScaleFactor()
   * @generated
   */
  EAttribute getLogScaleFactor_Params();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.LogScaleFactor#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see ca.ubc.stat.blang.blangDsl.LogScaleFactor#getExpr()
   * @see #getLogScaleFactor()
   * @generated
   */
  EReference getLogScaleFactor_Expr();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.ModelParam <em>Model Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Param</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ModelParam
   * @generated
   */
  EClass getModelParam();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.ModelParam#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ModelParam#getName()
   * @see #getModelParam()
   * @generated
   */
  EAttribute getModelParam_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ca.ubc.stat.blang.blangDsl.ModelParam#getDeps <em>Deps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Deps</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ModelParam#getDeps()
   * @see #getModelParam()
   * @generated
   */
  EReference getModelParam_Deps();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.ModelParam#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ModelParam#getRight()
   * @see #getModelParam()
   * @generated
   */
  EReference getModelParam_Right();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.Dependency#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Dependency#getType()
   * @see #getDependency()
   * @generated
   */
  EReference getDependency_Type();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.Dependency#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Dependency#getName()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Name();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.Dependency#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Init</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Dependency#getInit()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Init();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Distribution <em>Distribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distribution</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Distribution
   * @generated
   */
  EClass getDistribution();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.Distribution#getClazz <em>Clazz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Clazz</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Distribution#getClazz()
   * @see #getDistribution()
   * @generated
   */
  EReference getDistribution_Clazz();

  /**
   * Returns the meta object for the containment reference list '{@link ca.ubc.stat.blang.blangDsl.Distribution#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Distribution#getParam()
   * @see #getDistribution()
   * @generated
   */
  EReference getDistribution_Param();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see ca.ubc.stat.blang.blangDsl.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.ConstParam <em>Const Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const Param</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ConstParam
   * @generated
   */
  EClass getConstParam();

  /**
   * Returns the meta object for the attribute '{@link ca.ubc.stat.blang.blangDsl.ConstParam#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see ca.ubc.stat.blang.blangDsl.ConstParam#getId()
   * @see #getConstParam()
   * @generated
   */
  EAttribute getConstParam_Id();

  /**
   * Returns the meta object for class '{@link ca.ubc.stat.blang.blangDsl.LazyParam <em>Lazy Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lazy Param</em>'.
   * @see ca.ubc.stat.blang.blangDsl.LazyParam
   * @generated
   */
  EClass getLazyParam();

  /**
   * Returns the meta object for the containment reference '{@link ca.ubc.stat.blang.blangDsl.LazyParam#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see ca.ubc.stat.blang.blangDsl.LazyParam#getExpr()
   * @see #getLazyParam()
   * @generated
   */
  EReference getLazyParam_Expr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BlangDslFactory getBlangDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl <em>Blang Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangModelImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getBlangModel()
     * @generated
     */
    EClass BLANG_MODEL = eINSTANCE.getBlangModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLANG_MODEL__NAME = eINSTANCE.getBlangModel_Name();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLANG_MODEL__IMPORT_SECTION = eINSTANCE.getBlangModel_ImportSection();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLANG_MODEL__VARS = eINSTANCE.getBlangModel_Vars();

    /**
     * The meta object literal for the '<em><b>Laws</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLANG_MODEL__LAWS = eINSTANCE.getBlangModel_Laws();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.VarsImpl <em>Vars</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.VarsImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getVars()
     * @generated
     */
    EClass VARS = eINSTANCE.getVars();

    /**
     * The meta object literal for the '<em><b>Random Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARS__RANDOM_VARS = eINSTANCE.getVars_RandomVars();

    /**
     * The meta object literal for the '<em><b>Param Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARS__PARAM_VARS = eINSTANCE.getVars_ParamVars();

    /**
     * The meta object literal for the '<em><b>Consts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARS__CONSTS = eINSTANCE.getVars_Consts();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.RandomImpl <em>Random</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.RandomImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getRandom()
     * @generated
     */
    EClass RANDOM = eINSTANCE.getRandom();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANDOM__TYPE = eINSTANCE.getRandom_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANDOM__NAME = eINSTANCE.getRandom_Name();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.ParamVarImpl <em>Param Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.ParamVarImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getParamVar()
     * @generated
     */
    EClass PARAM_VAR = eINSTANCE.getParamVar();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM_VAR__TYPE = eINSTANCE.getParamVar_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_VAR__NAME = eINSTANCE.getParamVar_Name();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.ConstImpl <em>Const</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.ConstImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getConst()
     * @generated
     */
    EClass CONST = eINSTANCE.getConst();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONST__TYPE = eINSTANCE.getConst_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONST__NAME = eINSTANCE.getConst_Name();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONST__RIGHT = eINSTANCE.getConst_Right();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.VarDeclImpl <em>Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.VarDeclImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getVarDecl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getVarDecl();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__TYPE = eINSTANCE.getVarDecl_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECL__NAME = eINSTANCE.getVarDecl_Name();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__RIGHT = eINSTANCE.getVarDecl_Right();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.LawsImpl <em>Laws</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.LawsImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getLaws()
     * @generated
     */
    EClass LAWS = eINSTANCE.getLaws();

    /**
     * The meta object literal for the '<em><b>Model Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAWS__MODEL_COMPONENTS = eINSTANCE.getLaws_ModelComponents();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.ModelComponentImpl <em>Model Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.ModelComponentImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getModelComponent()
     * @generated
     */
    EClass MODEL_COMPONENT = eINSTANCE.getModelComponent();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.SupportFactorImpl <em>Support Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.SupportFactorImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getSupportFactor()
     * @generated
     */
    EClass SUPPORT_FACTOR = eINSTANCE.getSupportFactor();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUPPORT_FACTOR__PARAMS = eINSTANCE.getSupportFactor_Params();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUPPORT_FACTOR__EXPR = eINSTANCE.getSupportFactor_Expr();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.LogScaleFactorImpl <em>Log Scale Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.LogScaleFactorImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getLogScaleFactor()
     * @generated
     */
    EClass LOG_SCALE_FACTOR = eINSTANCE.getLogScaleFactor();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOG_SCALE_FACTOR__PARAMS = eINSTANCE.getLogScaleFactor_Params();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOG_SCALE_FACTOR__EXPR = eINSTANCE.getLogScaleFactor_Expr();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.ModelParamImpl <em>Model Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.ModelParamImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getModelParam()
     * @generated
     */
    EClass MODEL_PARAM = eINSTANCE.getModelParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_PARAM__NAME = eINSTANCE.getModelParam_Name();

    /**
     * The meta object literal for the '<em><b>Deps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL_PARAM__DEPS = eINSTANCE.getModelParam_Deps();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL_PARAM__RIGHT = eINSTANCE.getModelParam_Right();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.DependencyImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY__TYPE = eINSTANCE.getDependency_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__NAME = eINSTANCE.getDependency_Name();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__INIT = eINSTANCE.getDependency_Init();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.DistributionImpl <em>Distribution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.DistributionImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getDistribution()
     * @generated
     */
    EClass DISTRIBUTION = eINSTANCE.getDistribution();

    /**
     * The meta object literal for the '<em><b>Clazz</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION__CLAZZ = eINSTANCE.getDistribution_Clazz();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION__PARAM = eINSTANCE.getDistribution_Param();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.ParamImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.ConstParamImpl <em>Const Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.ConstParamImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getConstParam()
     * @generated
     */
    EClass CONST_PARAM = eINSTANCE.getConstParam();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONST_PARAM__ID = eINSTANCE.getConstParam_Id();

    /**
     * The meta object literal for the '{@link ca.ubc.stat.blang.blangDsl.impl.LazyParamImpl <em>Lazy Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.ubc.stat.blang.blangDsl.impl.LazyParamImpl
     * @see ca.ubc.stat.blang.blangDsl.impl.BlangDslPackageImpl#getLazyParam()
     * @generated
     */
    EClass LAZY_PARAM = eINSTANCE.getLazyParam();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAZY_PARAM__EXPR = eINSTANCE.getLazyParam_Expr();

  }

} //BlangDslPackage
