/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.blangDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const Param</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.ConstParam#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see ca.ubc.stat.blang.blangDsl.BlangDslPackage#getConstParam()
 * @model
 * @generated
 */
public interface ConstParam extends Param
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see ca.ubc.stat.blang.blangDsl.BlangDslPackage#getConstParam_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link ca.ubc.stat.blang.blangDsl.ConstParam#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

} // ConstParam
