/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.blangDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Laws</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.ubc.stat.blang.blangDsl.Laws#getModelComponents <em>Model Components</em>}</li>
 * </ul>
 *
 * @see ca.ubc.stat.blang.blangDsl.BlangDslPackage#getLaws()
 * @model
 * @generated
 */
public interface Laws extends EObject
{
  /**
   * Returns the value of the '<em><b>Model Components</b></em>' containment reference list.
   * The list contents are of type {@link ca.ubc.stat.blang.blangDsl.ModelComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Components</em>' containment reference list.
   * @see ca.ubc.stat.blang.blangDsl.BlangDslPackage#getLaws_ModelComponents()
   * @model containment="true"
   * @generated
   */
  EList<ModelComponent> getModelComponents();

} // Laws
