/**
 * generated by Xtext 2.9.1
 */
package ca.ubc.stat.blang.blangDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ca.ubc.stat.blang.blangDsl.BlangDslPackage#getModelComponent()
 * @model
 * @generated
 */
public interface ModelComponent extends EObject
{
} // ModelComponent
