grammar ca.ubc.stat.blang.BlangDsl with org.eclipse.xtext.xbase.Xbase

generate blangDsl "http://www.ubc.ca/stat/blang/BlangDsl"

BlangModel:
	{BlangModel}
	('package' name=QualifiedName)?
	importSection=XImportSection?
	('model' '{'
		vars=Vars
		laws = Laws?
	'}')?
	;
	
Vars:
	{Vars}
	(randomVars += Random)*
	;

Random:
	'random' type=JvmTypeReference name=ValidID
;

VarDecl:
	type=JvmTypeReference? name=ValidID '=' right=XExpression
;

Laws:
	'laws' '{'
	'}'
;
