/*
 * generated by Xtext 2.24.0
 */
package ca.ubc.stat.blang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BlangDslStandaloneSetup extends BlangDslStandaloneSetupGenerated {

	public static void doSetup() {
		new BlangDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
