/*
 * generated by Xtext 2.24.0
 */
package ca.ubc.stat.blang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlangDslRuntimeModule extends AbstractBlangDslRuntimeModule {
}
