import blang.core.DeboxedName;
import blang.core.Model;
import blang.core.ModelBuilder;
import blang.core.ModelComponents;
import blang.core.Param;
import blang.core.RealVar;
import blang.inits.Arg;
import ca.ubc.stat.blang.StaticJavaUtils;
import java.util.function.Supplier;

@SuppressWarnings("all")
public class MyFile implements Model {
  public static class Builder implements ModelBuilder {
    @Arg
    public RealVar mu;
    
    @Arg
    public RealVar y;
    
    public MyFile build() {
      // For each optional type, either get the value, or evaluate the ?: expression
      final RealVar __mu = mu;
      final RealVar __y = y;
      // Build the instance after boxing params
      return new MyFile(
        __y, 
        () -> __mu
      );
    }
  }
  
  @Param
  private final Supplier<RealVar> $generated__mu;
  
  public RealVar getMu() {
    return $generated__mu.get();
  }
  
  private final RealVar y;
  
  public RealVar getY() {
    return y;
  }
  
  /**
   * Utility main method for posterior inference on this model
   */
  public static void main(final String[] arguments) {
    StaticJavaUtils.callRunner(Builder.class, arguments);
  }
  
  /**
   * Auxiliary method generated to translate:
   * mu
   */
  private static RealVar $generated__0(final RealVar mu, final RealVar y) {
    return mu;
  }
  
  /**
   * Auxiliary method generated to translate:
   * y
   */
  private static RealVar $generated__1(final RealVar mu, final RealVar y) {
    return y;
  }
  
  /**
   * Auxiliary method generated to translate:
   * mean
   */
  private static RealVar $generated__2(final RealVar mean) {
    return mean;
  }
  
  /**
   * Auxiliary method generated to translate:
   * mean
   */
  private static Supplier<RealVar> $generated__2_lazy(final RealVar mean) {
    return () -> $generated__2(mean);
  }
  
  /**
   * Auxiliary method generated to translate:
   * [mean.doubleValue ** 2]
   */
  private static RealVar $generated__3(final RealVar mean) {
    final RealVar _function = new RealVar() {
      public double doubleValue() {
        double _doubleValue = mean.doubleValue();
        return Math.pow(_doubleValue, 2);
      }
    };
    return _function;
  }
  
  /**
   * Auxiliary method generated to translate:
   * [mean.doubleValue ** 2]
   */
  private static Supplier<RealVar> $generated__3_lazy(final RealVar mean) {
    return () -> $generated__3(mean);
  }
  
  /**
   * Note: the generated code has the following properties used at runtime:
   *   - all arguments are annotated with a BlangVariable annotation
   *   - params additionally have a Param annotation
   *   - the order of the arguments is as follows:
   *     - first, all the random variables in the order they occur in the blang file
   *     - second, all the params in the order they occur in the blang file
   * 
   */
  public MyFile(@DeboxedName("y") final RealVar y, @Param @DeboxedName("mu") final Supplier<RealVar> $generated__mu) {
    this.$generated__mu = $generated__mu;
    this.y = y;
  }
  
  /**
   * A component can be either a distribution, support constraint, or another model  
   * which recursively defines additional components.
   */
  public ModelComponents components() {
    ModelComponents components = new ModelComponents();
    
    { // Code generated by: y | RealVar mean = mu ~ new Normal(mean, [mean.doubleValue ** 2])
      // Required initialization:
      RealVar mean = $generated__0($generated__mu.get(), y);
      // Construction and addition of the factor/model:
      components.add(
        new ca.ubc.stat.blang.tests.types.Normal(
          $generated__1($generated__mu.get(), y), 
          $generated__2_lazy(mean), 
          $generated__3_lazy(mean)
        )
        ,
        "y | RealVar mean = mu ~ new Normal(mean, [mean.doubleValue ** 2])"
      );
    }
    
    return components;
  }
}
